### ISSUE TITLE
Unable to run the package. TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by Amir-Ramezani** [yanpanlau/DDPG-Keras-Torcs#14]
Hi,

Thanks for your package and the article along.

Unfortunately, I am not able to test your package, receiving the following error after issuing command python ddpg.py in gym_torcs directory:

--
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GT 650M
major: 3 minor: 0 memoryClockRate (GHz) 0.885
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.73GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:948] Ignoring visible gpu device (device: 0, name: GeForce GT 650M, pci bus id: 0000:01:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
Now we build the model
Traceback (most recent call last):
  File "ddpg.py", line 162, in <module>
    playGame()
  File "ddpg.py", line 52, in playGame
    actor = ActorNetwork(sess, state_dim, action_dim, BATCH_SIZE, TAU, LRA)
  File "/home/learning/gym_torcs/ActorNetwork.py", line 25, in __init__
    self.model , self.weights, self.state = self.create_actor_network(state_size, action_size)   
  File "/home/learning/gym_torcs/ActorNetwork.py", line 54, in create_actor_network
    V = merge([Steering,Acceleration,Brake],mode='concat')          
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1528, in merge
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1188, in __init__
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 154, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1275, in call
    return K.concatenate(inputs, axis=self.concat_axis)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 716, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

--

Can you tell me what can be the problem?

Sincerely,

**Comment by yanpanlau** [comment]
Hi, what keras version do you using?

Also, can you run snakeoil3_gym.py ?



2017年3月4日 12:28 於 "AmirCognitive" <notifications@github.com> 寫道：

**Comment by Amir-Ramezani** [comment]
My Keras version is 1.1.0 and I can run snakeoil3_gym.py with python3 not with python (python 2.7).
For running your package I use python 2.7 since you mentioned it as a dependency.

**Comment by yanpanlau** [comment]
I honestly never saw this problem myself before. But i wonder if your
tensorflow version is too new? I tested myself last week and it works using
tenorflow r.0.12 i think

2017年3月4日 12:45 於 "AmirCognitive" <notifications@github.com> 寫道：

**Comment by Amir-Ramezani** [comment]
Actually I installed tensorflow from source recently and the version is 1.0.0!

Do you think I should do some (too many?) changes in the source code in order to make it work with tensorflow 1.0.0?

**Comment by tegg89** [comment]
I have same problem. My test environment is TF 1.0.0, Python 2.7, and Keras 1.2. Because of the latest version of Keras, I commented 'collect_trainable_weights' import function. Same error happened when I run ddpg.py file. However, running snakeoil3_gym.py works.

**Comment by yanadsl** [comment]
Hi, I have tried to use old tensorflow and keras by command
`sudo pip2 install keras==1.1 tensorflow-gpu==0.12.0`
and there's no error after this
seems the new version have a lot of changes

**Comment by yanpanlau** [comment]
Thanks for letting me know. Yeah I am still using TF v0.12 and I heard new
TF v1.0 is not really backward compatible.

**Comment by Amir-Ramezani** [comment]
I tried to use your actor and critic architecture for low dimensional implementation with tf 1.0.0 and Keras 2.0.

After all, from my point of view which is based on my experiments results the implementation does not converge, the algorithm does not learns to select proper actions or even near the proper ones. Maybe it is because of some changes I did in order to make it work with tf 1.0.0 or some changes in the new versions of tf or Keras. Perhaps since you are the author of this code you can help me to find the issue.

I explain about my observation, states, next states, actions, next actions, rewards and ys all are okay, it means I receive them and use them as batch to train the critic network. The main problems starts from where I expect the actor network to be trained properly so it can select the proper actions in time (could you tell me why did you use different values for your OU in compare with what that is mentioned in the paper?). One problem I noticed is that the actions (the value for steering, gas, brake) tend to change toward 1. after a few hundred steps and then stay there for the rest of training so they will be like [1. 1. 1.]. I am not sure if this is a problem of grads (critic grads w.r.t actions) or something else. While I was trying to make it work with tf 1.0 I did some minor changes in the actor network you defined, changed the init for output layers from Lambda shape to a custom initialization mainly because of its strange Lambda error. I notice some differences in your critic network with the original paper beside the lack of initializations for the normal layers in low dimensional and the number of nodes, is that first) they said they used relu for all layers, but you used linear as well which in turn maybe contributes to the large grads and that contributes to the actions tending to go toward 1, second) they used 2 hidden layers but you used 3. So the main problem is in actor network where it cannot learn to produce the proper actions.

Could you tell me what is your ideas about this issue? and also after how many episodes and steps your algorithm converges?

Thanks

**Comment by quhezheng** [comment]
@AmirCognitive 
You are right, I run into same issue. OU output are very confusing, the steering come out mostly as positive value, the policy seldom try negtive value.

The init lamada expression got trouble in Keras 2. I replaced it with RadomNormal()

**Comment by narutatsuri** [comment]
I had this same problem. 
When I ran my code in Python 3 no errors occurred, but when I use Python 2 the errors happen. 
I'm guessing it has something to do with the differences of how data types are treated between Python 2 and 3.

**Comment by JinQiangWang2021** [comment]
Today I also meet this question ,because my environment is TF1.3 , keras1.1, ubuntu16.04 and python2.7,
who solve this qustion? I have to ask for help. thanks

**Comment by narutatsuri** [comment]
@Jin0932 I solved it by using TF 1.0.0. I think it's probably because the developers updated TF in a way that it wan't backward compatible.
