### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by abhinavsagar** [yanpanlau/DDPG-Keras-Torcs#58]
Getting-
`Traceback (most recent call last):
  File "ddpg.py", line 1, in <module>
    from gym_torcs import TorcsEnv
  File "C:\Users\Win 10\gym_torcs\gym_torcs.py", line 5, in <module>
    import snakeoil3_gym as snakeoil3
  File "C:\Users\Win 10\gym_torcs\snakeoil3_gym.py", line 149
    except socket.error, emsg:
`

**Comment by agusvgomez** [comment]
Run: 
python2 ddpg.py
instead than just python

**Comment by agusvgomez** [comment]
Run:
python2 ddpg.py
instead than just python
