### ISSUE TITLE
ValueError: Shapes (3, ?, 1) and () are incompatible

### ISSUE THREAD

**Issue by agusvgomez** [yanpanlau/DDPG-Keras-Torcs#61]
I'm getting this error when I run ddpg.py:

Traceback (most recent call last):
  File "ddpg.py", line 162, in <module>
    playGame()
  File "ddpg.py", line 52, in playGame
    actor = ActorNetwork(sess, state_dim, action_dim, BATCH_SIZE, TAU, LRA)
  File "/home/marmesto/DDPG-Keras-Torcs/ActorNetwork.py", line 25, in __init__
    self.model , self.weights, self.state = self.create_actor_network(state_size, action_size)   
  File "/home/marmesto/DDPG-Keras-Torcs/ActorNetwork.py", line 54, in create_actor_network
    V = merge([Steering,Acceleration,Brake],mode='concat')          
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1528, in merge
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1188, in __init__
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 154, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1275, in call
    return K.concatenate(inputs, axis=self.concat_axis)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 716, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1297, in concat
    tensor_shape.scalar())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 1103, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (3, ?, 1) and () are incompatible

**Comment by 404hasbeenfound** [comment]
i have this problem before, it seems the tensorflow version is not compatable, then i change the tensorflow to 0.12, then it fixed.

**Comment by legobill** [comment]
I have this problem ,and my tensorflow is 1.12.0. can you tell me your tensorflow(0.12?)Specific version ?or how to solve it?thanks!

**Comment by hildebrandt-carl** [comment]
@legobill you can run:
```
pip install tensorflow==0.12
```

**Comment by legobill** [comment]
谢谢，已经搞定了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Carl Hildebrandt"<notifications@github.com&gt;; 
发送时间: 2020年2月14日(星期五) 凌晨1:43
收件人: "yanpanlau/DDPG-Keras-Torcs"<DDPG-Keras-Torcs@noreply.github.com&gt;; 
抄送: "花花世界.个人自由自在"<1986587179@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yanpanlau/DDPG-Keras-Torcs] ValueError: Shapes (3, ?, 1) and () are incompatible (#61)




@legobill you can run:
 pip install tensorflow==0.12
